# Generated by Django 5.1.6 on 2025-02-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Անուն')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Էլ․ հասցե։')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Բաժանորդ',
                'verbose_name_plural': 'Բաժանորդներ',
            },
        ),
    ]
