# Generated by Django 5.1.6 on 2025-02-20 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0003_rename_image_productimages_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopapi.product', verbose_name='Ապրանքի Նկարներ։'),
        ),
    ]
